#### 什么是 Exception 

简单来说就是系统发生了错误，导致原本的程序无法完成的情况，这种时候会尽可能把错误信息转化成有效的信息。

通常一套系统都会针对错误做处理，提供有效的错误信息。在 `javascript`中，最常见的抛出错误的方法就是使用`Error`，这个`Error`就是`Exception`的概念，把错误信息包装起来变成统一的格式：

```tsx
throw new Error('系统发生了错误');
```

#### nest 的错误处理机制

在抛出错误后，需要有个机制去捕捉这些错误，并从中提取信息整理出规范的格式返回，`nest`在底层已经帮我们做了一套错误处理机制 `Exception filter`，它会去捕捉抛出的错误，并将错误信息、`Http Code`进行友善的包装：

![Exception filter](/Users/lynnlee/学习区/learn-nest/images/exception-filter.drawio.png)

我们可以做一个小验证，修改`app.controller.ts`的内容，在`getHello`方法内抛出错误：

```tsx
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    throw new Error('出错啦～');
    return this.appService.getHello();
  }
}
```

接着访问这个路由你会发现报错并返回了如下格式：

![error](/Users/lynnlee/学习区/learn-nest/images/error-500.png)

为什么响应的错误信息跟我们代码抛出的`出错啦～`不一致呢？

原因是`nest`内部的`Exception filter`会去监测抛出的错误是什么类型，它只能够接受`nest`内置的`HttpException`和继承该类的`Exception`，若不属于这类型的错误就会直接抛出`Internal server error`。



#### 标准的Exception

`nest`内置的标准`Exception`就是`HttpException`， 它是一个标准的`class`，提供非常弹性的使用体验，通过给定`constructor`两个必填的参数来自定义错误信息和`httpCode`。

示例：

```tsx
import { Controller, Get, HttpException, HttpStatus } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    throw new HttpException('出错啦~', HttpStatus.BAD_REQUEST);
    return this.appService.getHello();
  }
}
```

这次就跟我们的错误信息保持一致了：

![](/Users/lynnlee/学习区/learn-nest/images/standard-exception.png)

那如果我们不想要`nest`提供的响应体怎么办？可以把第一个参数改成对象的形式，`nest`会自动覆盖格式：

```tsx
import { Controller, Get, HttpException, HttpStatus } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    throw new HttpException(
      {
        code: HttpStatus.BAD_REQUEST,
        msg: '出错啦～',
      },
      HttpStatus.BAD_REQUEST,
    );
    return this.appService.getHello();
  }
}

```

返回：

![](/Users/lynnlee/学习区/learn-nest/images/custom-standard-exception.png)

#### 内置的 Http Exception

`nest` 有内置的一套基于`HttpException`的`Exception`，让开发者根据不同的错误来选用不同的`Exception`:

| 内置 Exception                     | 表示/含义                                                    |
| ---------------------------------- | ------------------------------------------------------------ |
| `BadRequestException`              | 表示客户端发送了无效的请求，例如缺少必需的参数或格式不正确的参数。 |
| `UnauthorizedException`            | 表示客户端未经授权访问受保护的资源。                         |
| `NotFoundException`                | 表示请求的资源不存在。                                       |
| `ForbiddenException`               | 表示客户端没有访问请求资源的权限。                           |
| `NotAcceptableException`           | 表示服务器无法提供客户端请求的内容类型。                     |
| `RequestTimeoutException`          | 表示客户端请求超时。                                         |
| `ConflictException`                | 表示请求的操作与当前资源状态冲突。                           |
| `GoneException`                    | 表示请求的资源已经不存在。                                   |
| `HttpVersionNotSupportedException` | 表示Http 版本不支持异常                                      |
| `PayloadTooLargeException`         | 表示请求的负载太大，服务器无法处理。                         |
| `UnsupportedMediaTypeException`    | 表示请求的媒体类型不受支持。                                 |
| `UnprocessableEntityException`     | 表示无法处理的实体异常                                       |
| `InternalServerErrorException`     | 表示内部服务器错误异常                                       |
| `NotImplementedException`          | 表示请求的操作尚未实现。                                     |
| `ImATeapotException`               | 表示HTTP **`418 I'm a teapot`** 客户端错误响应代码表示服务器拒绝冲泡咖啡，因为它是个茶壶。该错误是超文本咖啡壶控制协议的参考，和 1998 年愚人节的玩笑。 |
| `MethodNotAllowedException`        | 状态码 **`405 Method Not Allowed`** 表明服务器禁止了使用当前 HTTP 方法的请求。 |
| `BadGatewayException`              | 表示网关或代理服务器从上游服务器接收到无效的响应。           |
| `ServiceUnavailableException`      | 表示服务当前不可用。                                         |
| `GatewayTimeoutException`          | 表示网关或代理服务器在等待上游服务器响应时超时。             |
| `PreconditionFailedException`      | 在 HTTP 协议中，响应状态码 **412 Precondition Failed**（先决条件失败）表示客户端错误，意味着对于目标资源的访问请求被拒绝。 |

这里我们选择`BadRequestException`进行测试，修改`app.controller.ts`：

```tsx
import { BadRequestException, Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    throw new BadRequestException('出错啦～');
    return this.appService.getHello();
  }
}
```

> 注意： 所有的内置`Exception`都可以传入`options`覆盖`nest`的默认格式。

```tsx
import { BadRequestException, Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    throw new BadRequestException({msg: '出错啦～'});
    return this.appService.getHello();
  }
}
```



#### 自定义 `Exception`

前面有提到过`HttpException`是标准的`Class`，这表示我们可以通过继承`HttpException`来完成自定义的`Exception`。

不过大多数情况都不需要我们自定义`Exception`，因为`nest`提供的`Exception`已经够用了，不过我们还是来了解下如何自定义`Exception`，我们在`src`目录下新增一个`exceptions`目录，接着新建一个`custom.exception.ts`文件，内容如下：

```tsx
import { HttpException, HttpStatus } from '@nestjs/common';

export class CustomException extends HttpException {
  constructor() {
    super('自定义 Exception', HttpStatus.INTERNAL_SERVER_ERROR);
  }
}
```

修改`app.controller.ts`：

```tsx
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';
import { CustomException } from './exceptions/custom.exception';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    // 使用自定义的 Exception
    throw new CustomException();
    return this.appService.getHello();
  }
}
```

![](/Users/lynnlee/学习区/learn-nest/images/custom-exception.png)

#### 自定义 `Exception filter`

如果希望完全掌握错误处理机制的话，`nest`是可以自定义`Exception filter`的，通过这样的方式来添加`log`，或者是直接在这个层级定义响应体格式。`Exception Filter `必须要使用`@Catch(...exceptions: Type<any>[])`装饰器来捕捉错误，可以指定要捕捉特定类型的`Exception`，也可以捕捉全部的错误，若要捕捉全部就不需要带任何参数到`@Catch`里面，另外，还需要该`Class`去实现`ExceptionFilter<T>`接口，它会限制一定要实现`catch(exception: T, host: ArgumentsHost)`这个方法。

我们在`src`目录下新建`filters`，接着创建文件`http-exception.filter.ts`:

```tsx
import {
  ArgumentsHost,
  Catch,
  ExceptionFilter,
  HttpException,
} from '@nestjs/common';
import { Response } from 'express';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter<HttpException> {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp(); // 获取当前的上下文
    const response = ctx.getResponse<Response>(); // 取回 response
    const status = exception.getStatus(); // 拿到错误状态码
    const message = exception.message; // 拿到错误 message
    const timestamp = new Date().toISOString();

    // 组装响应体格式
    const responseObject = {
      code: status,
      message,
      timestamp,
    };

    // 返回给客户端
    response.status(status).json(responseObject);
  }
}

```

这个示例主要是希望可以捕捉`HttpException`，在捕捉时会获得该`Exception`以及一个叫做`ArgumentsHost`的东西，通过它我们可以获取`Response`属性，进而返回自定义格式给客户端：

```tsx
{
    "code": 500,
    "message": "自定义 Exception",
    "timestamp": "2023-07-20T05:43:29.458Z"
}
```

##### ArgumentsHost

是一个用来取得当前请求相关参数的`Class`，它是一个抽象概念，由于`nest`能够实现`REST API` 、 `WebSocket` 以及`MicroService` ，每个架构的参数都会有些不同，这时候通过抽象的方式做统一是最合适的，以`Express`作为底层的`REST API`来说，它封装了`Request`、`Response` 以及`NextFunction`，但如果是`MicroService`的话，封装的内容又不同了，所以`ArgumentsHost`提供了一些共同层面来取的这些底层的信息。

- 取得当前应用类型

通过 `getType()`取的当前应用的类型，以 `REST API ` 来说，会得到字符串`http`:

```tsx
host.getType() === 'http'; // true
```

- 取得封装参数

通过`getArgs()`取得当前应用类型下封装的参数，以`Express`为底层的`REST API `来说，即`Request`、`Response`、`NextFunction`:

```tsx
const [req, res, next] = host.getArgs();
```

`getArgs()`返回的是一个数组，`nest`提供了通过索引值取得参数的方法 `getArgByIndex(index: number)`：

```tsx
const req = host.getArgByIndex(0);
```

以上的方法都是通过对数组的操作来取得相关的参数，但这样在面对不同架构的重用会有困难，毕竟不同的架构封装的参数会有不同，这时候就可以使用下方的方式来取得相关内容：

```tsx
const rpcCtx: RpcArgumentsHost = host.switchToRpc(); // MicroService 的封装内容
const httpCtx: HttpArgumentsHost = host.switchToHttp(); // REST 的封装内容
const wsCtx: WsArgumentsHost = host.switchToWs(); // WebSocket 的封装内容
```



##### 使用 Exception filter

使用的方式十分简单，粗略的分成两种：

- 单一资源： 在 `Controller` 的方法中使用 `@UseFilters`装饰器，只会针对该方法生效。
- `Controller`: 直接在`Controller`上使用`@UseFilters`装饰器，会针对整个`Controller`中的方法生效。

`@UseFilters`装饰器的参数是传入要使用的`Exception filter`。

下面是单一资源的示例，修改`app.controller.ts`：

```tsx
import {
  BadRequestException,
  Controller,
  Get,
  UseFilters,
} from '@nestjs/common';
import { AppService } from './app.service';
import { HttpExceptionFilter } from './filters/http-exception.filter';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  @UseFilters(HttpExceptionFilter) // 只会对该方法生效
  getHello(): string {
    throw new BadRequestException('出错啦～');
    return this.appService.getHello();
  }
}

```

下面是 `Controller` 使用 `Exception filter`的示例：

```tsx
import {
  BadRequestException,
  Controller,
  Get,
  UseFilters,
} from '@nestjs/common';
import { AppService } from './app.service';
import { HttpExceptionFilter } from './filters/http-exception.filter';

@Controller()
@UseFilters(HttpExceptionFilter) // 会对整个控制器内的方法生效
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    throw new BadRequestException('出错啦～');
    return this.appService.getHello();
  }
}

```

> 注意： `@UseFilters`传入的`Exception filter`可以是`class`本身，也可以是实例，它们的差别在于使用`class`会通过`nest`依赖注入进行实例的管理，而传入实例的话则不会，所以没有什么特别需要的话，还是以传入`class`为主。

##### 全局 `Exception filter`

如果我的`Exception filter` 是要使用到每一个资源上的话，不就要替每个`Controller`都添加`@UseFilters`装饰器吗？

放心，`nest`非常贴心的提供了配置在全局的方法，只需要在`main.ts`中增加内容：

```tsx
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { HttpExceptionFilter } from './filters/http-exception.filter';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.useGlobalFilters(new HttpExceptionFilter()); // 全局 Exception Filter

  await app.listen(3000);
}
bootstrap();

```

##### 用依赖注入实现的全局`Exception filter`

上面的方法是通过模块外部完成全局配置的，如果希望通过依赖注入的方式来实现全局`Exception filter`有什么办法吗？

`nest` 确实也有提供解决方案，只需要在**任一模块**进行配置，既然是用依赖注入的方式，那就跟`Provider`脱不了关系，通过指定`token`为`APP_FILTER`来实现，`useClass`指定要建立实例的`Exception filter`：

```
import { Module } from '@nestjs/common';
import { APP_FILTER } from '@nestjs/core';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { HttpExceptionFilter } from './filters/http-exception.filter';

@Module({
  imports: [],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_FILTER, // nest/core 提供的 token
      useClass: HttpExceptionFilter, // 要注入的 exception filter
    },
  ],
})
export class AppModule {}

```

> 注意： 这里是在`AppModule`中进行全局`Exception filter`注入，但是实际上，你在任何模块注入都可以实现全局`Exception filter`。
